org.gradle.jvmargs=-Xms256m -Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC -XX:+UseStringDeduplication -Dfile.encoding=UTF-8
kotlin.daemon.jvm.options=-Xms128m -Xmx1536m -XX:MaxMetaspaceSize=384m -XX:+UseG1GC
android.aapt2.enableDaemons=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.jvmargs.osspecific.windows=-Dfile.encoding=UTF-8
org.gradle.caching=true
